#!/usr/bin/env bash
# Server-01 login commands

# Setting up the SSH agent
eval $("ssh-agent")

# Path to identityFile
ssh-add ~/.ssh/id_rsa

# Username and IP Address 
ssh -i ~/.ssh/id_rsa ubuntu@35.153.232.154
